{{- if .Values.canaryIngress.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demochart.fullname" . }}-can
  labels:
{{ include "demochart.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "demochart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      deployment: canary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "demochart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        deployment: canary
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.canaryImage.repository }}:{{ .Values.canaryImage.tag }}"
          imagePullPolicy: {{ .Values.canaryImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
